version: 1

providers:
  - php
  - nodejs

phases:
  setup:
    nixPkgs:
      - mysql
      - mariadb
      - libiconv
  install:
    cmds:
      - composer install --no-dev --optimize-autoloader
      - npm install && npm run build
  build:
    cmds:
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan storage:link

start:
  cmd: |
    php artisan migrate --force
    php -S 0.0.0.0:$PORT -t public