version: 1

providers:
  - php

phases:
  setup:
    nixPkgs:
      - mysql
      - mariadb-client
  install:
    cmds:
      - composer install --no-dev --optimize-autoloader
  build:
    cmds:
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

start:
  cmd: php -S 0.0.0.0:$PORT -t public